#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: ticket_system
#    password: ${DB_PASSWORD}
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#
#server:
#  port: 8080